### ISSUE TITLE
Optimize local environment for e2e testing

### ISSUE THREAD

**Issue by ekraffmiller** [IQSS/dataverse-frontend#371]
Depending on the machine resources, some e2e tests are failing in a local development environment, even though they are passing in Github actions.  
To address this, we need to investigate some aspects of the environment that may be optimized:
- docker container sizes
- timeouts for e2e tests
- docker platform configuration

This issue is related to the QA discussion in this PR: https://github.com/IQSS/dataverse-frontend/pull/360#issuecomment-2034439860

**Comment by GPortas** [comment]
`MacBook-Pro-668:dataverse-frontend guillermoportasgonzalez$ npm run test:e2e

> dataverse-frontend@0.1.0 test:e2e
> cypress run --e2e


DevTools listening on ws://127.0.0.1:56548/devtools/browser/921ca7c3-cbb0-4a3c-95e6-6a39881fb339
Missing baseUrl in compilerOptions. tsconfig-paths will be skipped

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        12.14.0                                                                        │
  │ Browser:        Electron 106 (headless)                                                        │
  │ Node Version:   v19.6.0 (/Users/guillermoportasgonzalez/.nvm/versions/node/v19.6.0/bin/no      │
  │                 de)                                                                            │
  │ Specs:          9 found (integration/datasets/DatasetJSDataverseRepository.spec.ts, integratio │
  │                 n/files/FileJSDataverseRepository.spec.ts, integration/metadata-block-info/Met │
  │                 adataBlockInfoJSDataverseRepository.spec.ts, e2e/sections/dataset/Dataset.spec │
  │                 .tsx, e2e/sections/col...)                                                     │
  │ Searched:       tests/e2e-integration/**/*.spec.{js,jsx,ts,tsx}                                │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  integration/datasets/DatasetJSDataverseRepository.spec.ts                       (1 of 9)


  Dataset JSDataverse Repository
    1) "before all" hook for "gets the dataset by persistentId"


  0 passing (3s)
  1 failing

  1) Dataset JSDataverse Repository
       "before all" hook for "gets the dataset by persistentId":
     CypressError: `cy.visit()` failed trying to load:

http://localhost:8000/

The response we received from your web server was:

  > 500: Internal Server Error

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Dataset JSDataverse Repository`
      at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:147666:84)
      at visitFailedByErr (http://localhost:8000/__cypress/runner/cypress_runner.js:147074:12)
      at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:147649:13)
      at tryCatcher (http://localhost:8000/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:8000/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:8000/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:8000/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://localhost:8000/__cypress/runner/cypress_runner.js:16857:18)
      at _drainQueueStep (http://localhost:8000/__cypress/runner/cypress_runner.js:13451:12)
      at _drainQueue (http://localhost:8000/__cypress/runner/cypress_runner.js:13444:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:13460:5)
      at Async.drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:13330:14)
  From Your Spec Code:
      at Context.eval (http://localhost:8000/__cypress/tests?p=tests/support/e2e.ts:51236:8)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        11                                                                               │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      10                                                                               │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     2 seconds                                                                        │
  │ Spec Ran:     integration/datasets/DatasetJSDataverseRepository.spec.ts                        │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  integration/files/FileJSDataverseRepository.spec.ts                             (2 of 9)


  File JSDataverse Repository
    1) "before all" hook for "gets all the files by dataset persistentId with the basic information"


  0 passing (6s)
  1 failing

  1) File JSDataverse Repository
       Get all files by dataset persistentId
         "before all" hook for "gets all the files by dataset persistentId with the basic information":
     CypressError: `cy.visit()` failed trying to load:

http://localhost:8000/

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `File JSDataverse Repository`
      at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:147666:84)
      at visitFailedByErr (http://localhost:8000/__cypress/runner/cypress_runner.js:147074:12)
      at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:147649:13)
      at tryCatcher (http://localhost:8000/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:8000/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:8000/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:8000/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://localhost:8000/__cypress/runner/cypress_runner.js:16857:18)
      at _drainQueueStep (http://localhost:8000/__cypress/runner/cypress_runner.js:13451:12)
      at _drainQueue (http://localhost:8000/__cypress/runner/cypress_runner.js:13444:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:13460:5)
      at Async.drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:13330:14)
  From Your Spec Code:
      at Context.eval (http://localhost:8000/__cypress/tests?p=tests/support/e2e.ts:51236:8)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        22                                                                               │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      21                                                                               │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     6 seconds                                                                        │
  │ Spec Ran:     integration/files/FileJSDataverseRepository.spec.ts                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  integration/metadata-block-info/MetadataBlockInfoJSDataverseReposito            (3 of 9)
            ry.spec.ts                                                                              


  Metadata Block Info JSDataverse Repository
    1) "before all" hook for "gets the metadataBlockInfo by name"


  0 passing (1s)
  1 failing

  1) Metadata Block Info JSDataverse Repository
       "before all" hook for "gets the metadataBlockInfo by name":
     CypressError: `cy.visit()` failed trying to load:

http://localhost:8000/

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Metadata Block Info JSDatav...`
      at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:147666:84)
      at visitFailedByErr (http://localhost:8000/__cypress/runner/cypress_runner.js:147074:12)
      at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:147649:13)
      at tryCatcher (http://localhost:8000/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:8000/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:8000/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:8000/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://localhost:8000/__cypress/runner/cypress_runner.js:16857:18)
      at _drainQueueStep (http://localhost:8000/__cypress/runner/cypress_runner.js:13451:12)
      at _drainQueue (http://localhost:8000/__cypress/runner/cypress_runner.js:13444:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:13460:5)
      at Async.drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:13330:14)
  From Your Spec Code:
      at Context.eval (http://localhost:8000/__cypress/tests?p=tests/support/e2e.ts:51236:8)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     integration/metadata-block-info/MetadataBlockInfoJSDataverseRepository.spec.ts   │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  e2e/sections/dataset/Dataset.spec.tsx                                           (4 of 9)


  Dataset
    1) "before all" hook for "successfully loads a dataset in draft mode"


  0 passing (1s)
  1 failing

  1) Dataset
       Visit the Dataset Page as a logged in user
         "before all" hook for "successfully loads a dataset in draft mode":
     CypressError: `cy.visit()` failed trying to load:

http://localhost:8000/

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Dataset`
      at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:147666:84)
      at visitFailedByErr (http://localhost:8000/__cypress/runner/cypress_runner.js:147074:12)
      at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:147649:13)
      at tryCatcher (http://localhost:8000/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:8000/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:8000/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:8000/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://localhost:8000/__cypress/runner/cypress_runner.js:16857:18)
      at _drainQueueStep (http://localhost:8000/__cypress/runner/cypress_runner.js:13451:12)
      at _drainQueue (http://localhost:8000/__cypress/runner/cypress_runner.js:13444:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:13460:5)
      at Async.drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:13330:14)
  From Your Spec Code:
      at Context.eval (http://localhost:8000/__cypress/tests?p=tests/support/e2e.ts:51236:8)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        23                                                                               │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      22                                                                               │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     1 second                                                                         │
  │ Spec Ran:     e2e/sections/dataset/Dataset.spec.tsx                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  e2e/sections/collection/Collection.spec.ts                                      (5 of 9)


  Collection Page
    1) "before all" hook for "successfully loads root collection when accessing the home"


  0 passing (829ms)
  1 failing

  1) Collection Page
       "before all" hook for "successfully loads root collection when accessing the home":
     CypressError: `cy.visit()` failed trying to load:

http://localhost:8000/

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Collection Page`
      at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:147666:84)
      at visitFailedByErr (http://localhost:8000/__cypress/runner/cypress_runner.js:147074:12)
      at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:147649:13)
      at tryCatcher (http://localhost:8000/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:8000/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:8000/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:8000/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://localhost:8000/__cypress/runner/cypress_runner.js:16857:18)
      at _drainQueueStep (http://localhost:8000/__cypress/runner/cypress_runner.js:13451:12)
      at _drainQueue (http://localhost:8000/__cypress/runner/cypress_runner.js:13444:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:13460:5)
      at Async.drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:13330:14)
  From Your Spec Code:
      at Context.eval (http://localhost:8000/__cypress/tests?p=tests/support/e2e.ts:51236:8)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        12                                                                               │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      11                                                                               │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     e2e/sections/collection/Collection.spec.ts                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  e2e/sections/create-dataset/CreateDatasetForm.spec.tsx                          (6 of 9)


  Create Dataset
    1) "before all" hook for "visits the Create Dataset Page as a logged in user"


  0 passing (632ms)
  1 failing

  1) Create Dataset
       "before all" hook for "visits the Create Dataset Page as a logged in user":
     CypressError: `cy.visit()` failed trying to load:

http://localhost:8000/

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Create Dataset`
      at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:147666:84)
      at visitFailedByErr (http://localhost:8000/__cypress/runner/cypress_runner.js:147074:12)
      at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:147649:13)
      at tryCatcher (http://localhost:8000/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:8000/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:8000/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:8000/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://localhost:8000/__cypress/runner/cypress_runner.js:16857:18)
      at _drainQueueStep (http://localhost:8000/__cypress/runner/cypress_runner.js:13451:12)
      at _drainQueue (http://localhost:8000/__cypress/runner/cypress_runner.js:13444:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:13460:5)
      at Async.drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:13330:14)
  From Your Spec Code:
      at Context.eval (http://localhost:8000/__cypress/tests?p=tests/support/e2e.ts:51236:8)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        3                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      2                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     e2e/sections/create-dataset/CreateDatasetForm.spec.tsx                           │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  integration/info/infrastructure/repositories/DataverseInfoJSDatavers            (7 of 9)
            eRepository.spec.ts                                                                     


  DataverseInfo JSDataverse Repository
    ✓ gets the dataverse version number (21493ms)


  1 passing (22s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     21 seconds                                                                       │
  │ Spec Ran:     integration/info/infrastructure/repositories/DataverseInfoJSDataverseRepository. │
  │               spec.ts                                                                          │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  e2e/sections/file/File.spec.tsx                                                 (8 of 9)


  File
    Visit the File Page as a logged in user
      1) successfully loads a file in draft mode
      ✓ successfully loads a published file when the user is not authenticated (52500ms)
      ✓ loads page not found when the user is not authenticated and tries to access a draft (16734ms)
      ✓ successfully loads a file when passing the id and datasetVersion (19004ms)
      ✓ loads page not found when passing a wrong id (10316ms)
      ✓ loads correctly the breadcrumbs (14278ms)


  5 passing (2m)
  1 failing

  1) File
       Visit the File Page as a logged in user
         successfully loads a file in draft mode:
     CypressError: `cy.wrap()` timed out waiting `4000ms` to complete.

You called `cy.wrap()` with a promise that never resolved.

To increase the timeout, use `{ timeout: number }`

https://on.cypress.io/wrap
      at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:146653:78)
      at tryCatcher (http://localhost:8000/__cypress/runner/cypress_runner.js:18744:23)
      at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:13866:41)
      at tryCatcher (http://localhost:8000/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:8000/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:8000/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:8000/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://localhost:8000/__cypress/runner/cypress_runner.js:16857:18)
      at _drainQueueStep (http://localhost:8000/__cypress/runner/cypress_runner.js:13451:12)
      at _drainQueue (http://localhost:8000/__cypress/runner/cypress_runner.js:13444:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:13460:5)
      at Async.drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:13330:14)
  From Your Spec Code:
      at Context.eval (http://localhost:8000/__cypress/tests?p=tests/e2e-integration/e2e/sections/file/File.spec.tsx:10045:12)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        6                                                                                │
  │ Passing:      5                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     2 minutes, 8 seconds                                                             │
  │ Spec Ran:     e2e/sections/file/File.spec.tsx                                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  integration/users/infrastructure/repositories/UserJSDataverseReposit            (9 of 9)
            ory.spec.ts                                                                             


  User JSDataverse Repository
    ✓ gets the authenticated user (7925ms)
    ✓ removes the authenticated user (3379ms)


  2 passing (11s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        2                                                                                │
  │ Passing:      2                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     11 seconds                                                                       │
  │ Spec Ran:     integration/users/infrastructure/repositories/UserJSDataverseRepository.spec.ts  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  integration/datasets/DatasetJSDatav      00:02       11        -        1        -       10 │
  │    erseRepository.spec.ts                                                                      │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  integration/files/FileJSDataverseRe      00:06       22        -        1        -       21 │
  │    pository.spec.ts                                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  integration/metadata-block-info/Met      970ms        1        -        1        -        - │
  │    adataBlockInfoJSDataverseRepository                                                         │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  e2e/sections/dataset/Dataset.spec.t      00:01       23        -        1        -       22 │
  │    sx                                                                                          │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  e2e/sections/collection/Collection.      745ms       12        -        1        -       11 │
  │    spec.ts                                                                                     │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  e2e/sections/create-dataset/CreateD      557ms        3        -        1        -        2 │
  │    atasetForm.spec.tsx                                                                         │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  integration/info/infrastructure/rep      00:21        1        1        -        -        - │
  │    ositories/DataverseInfoJSDataverseR                                                         │
  │    epository.spec.ts                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  e2e/sections/file/File.spec.tsx          02:08        6        5        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  integration/users/infrastructure/re      00:11        2        2        -        -        - │
  │    positories/UserJSDataverseRepositor                                                         │
  │    y.spec.ts                                                                                   │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  7 of 9 failed (78%)                      02:53       81        8        7        -       66  

MacBook-Pro-668:dataverse-frontend guillermoportasgonzalez$ 
  [Restaurado: 15 abr 2024, 13:25:52]
Last login: Mon Apr 15 13:25:52 on ttys006
Restored session: lunes, 15 de abril de 2024, 12:47:59 WEST

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.`
